### PR TITLE
added System76 Lemur HCL

### PR DESCRIPTION
**Pull request by mfc**
from: https://groups.google.com/d/msg/qubes-users/qyrnohmq17E/ftUGPLNeBQAJ

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
Would you mind replacing the `FIXME`s as appropriate?

**Comment by mfc** [comment]
it's not my hcl, so i guess we should ask the submitter to fill in the FIXMEs.

**Comment by andrewdavidwong** [comment]
Was this HCL submitted on qubes-users? If so, do you mind if we close this PR and let @tasket handle it? He's our new HCL maintainer. :)

**Comment by mfc** [comment]
yes linked in first post (https://groups.google.com/d/msg/qubes-users/qyrnohmq17E/ftUGPLNeBQAJ). perfect! send to @tasket

**Pull request closed without merging**
