### PR TITLE
System76 Darter & Asus All Series HCLs

### PR DESCRIPTION
**Pull request by SvenSemmler**
- new HCLs from last two days
- some cosmetic changes to the model name of Asus All Series entires
- fixing chipset 'Comet Lake' in an old entry

### CODE REVIEW

**Comment by SvenSemmler** [comment]
@fepitre, sorry to bother you again, but now I have this issue: "The current user is not authorized to access the job log." 

@andrewdavidwong yamllint is happy and I assume it's the spelling check again. Please review and merge.

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by marmarek** [comment]
```
The following new unknown spellings were introduced:
    +10510U
    +de5eab8
In addition, the following suspicious spellings were eliminated:
    -9b61
The introduced suspects in context are:
./_hcl/System76-Darter_Pro-20210117-224438.yml:23:  Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
./_hcl/System76-Darter_Pro-20210117-224438.yml:25:  i7-10510U
```
I can access it without logging into gitlab at all, so it should work for you too...

**Comment by SvenSemmler** [comment]
> I can access it without logging into gitlab at all, so it should work for you too...

Today it does, yesterday I got the quoted error message. Maybe a temporary problem. Thank you for checking.

**Pull request merged**
