### PR TITLE
add Dell Latitude 7285 & ThinkPad T490

### PR DESCRIPTION
**Pull request by SvenSemmler**

### CODE REVIEW

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
@andrewdavidwong something changed: I no longer see the failing build with the spellchecker and "testdeploy" commands don't work either. Nevertheless ... the YML files are clean, reviewed and pass yamllint on my machine. Please merge at your convenience.

**Comment by andrewdavidwong** [comment]
> @andrewdavidwong something changed: I no longer see the failing build with the spellchecker and "testdeploy" commands don't work either. Nevertheless ... the YML files are clean, reviewed and pass yamllint on my machine. Please merge at your convenience.

@fepitre, it looks like CI may not be working here. Could you take a look?

**Pull request merged**
