### PR TITLE
yamllint, new HCLs & cleanup

### PR DESCRIPTION
**Pull request by SvenSemmler**
- adding a few new HCL entries
- adding yamllint config file (to supress line length error)
- necessary changes to make yamllint happy with all entires
- removed entries for Purism crowd funding (successfully closed) and prototype as they did not contain any useful information (hardware? does it work? etc); there are several Purism HCL entries for production laptops in the list.

### CODE REVIEW

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
@marmarek: I get a 403 (access forbidden!) when following the "view deployment" link. This is new.

**Comment by marmarek** [comment]
This is because the site build failed. See link to the build log in "checks" section below.

**Comment by SvenSemmler** [comment]
@marmarek yes, thank you. Sorry.

**Comment by SvenSemmler** [comment]
@andrewdavidwong @marmarek  ... there are probably many HCL files checked in right now that would fail these test. I'll address that a.s.a.p.

**Comment by SvenSemmler** [comment]
will figure this out and fix it globally, then reopen when ready. sorry for the noise.

**Comment by SvenSemmler** [comment]
@andrewdavidwong please ignore this PR until I notify you. I reopened it so I can see the CI results.

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
@marmarek I need a little help please: I don't understand why the CI still fails. 

@andrewdavidwong, except for the failing CI check this PR is ready. The test deployment worked and the result looks OK to me.

**Comment by andrewdavidwong** [comment]
You can see the full log by clicking "Details" next to the failed check on this page, then the "Jobs" tab, then the "X Failed" button, then scrolling down to the bottom.

In this case, the log shows that the CI check is failing because:

```
The following new unknown spellings were introduced:
    +'3
    +'4
    +'R3
    +0'
    +100'
    +2'
    +2349S7W
    +4417U
    +9b61
    +G1ET73WW
    +S71
    +UX331UAL
    +ZenBook
    +by0xxx
    +michaelaltfield
    +nortiusmediae
```

The spell checker works by flagging all unknown spellings. In this case, it looks like all of these are probably intentional. If we proceed to merge this PR with these unknown spellings, they will be added to the whitelist and won't be flagged in the future. In other words, the mere fact that the word is flagged does not necessarily mean that it is wrong or that anything needs to be changed. It just means that the spell checker has not yet added it to the whitelist.

**Pull request merged**
