### PR TITLE
Add (18) HCL reports

### PR DESCRIPTION
**Pull request by tasket**
ASUS Z97-Pro-gamer
BIOSTAR MCP6P3
Sony SVP11216PXB

### CODE REVIEW

**Comment by andrewdavidwong** [comment]
@tasket: Let's not set the precedent of adding special text to a blue "unknown" TPM cell. That would be inconsistent with the legend, which says (for blue): "a blank cell indicates we lack information."

(Unless we're willing to change the HCL entirely to make everything consistent.)

**Comment by tasket** [comment]
@andrewdavidwong OK, I think you mean the BIOSTAR file. It was submitted that way, so I thought the script might have added the "unknown" text.

**Comment by tasket** [comment]
There is a signature issue with commit 51183b4 "Correct tmp field". It shows up with green 'Verified' badge but also with red 'X'.

Also added another entry for Thinkpad T460s.

**Comment by marmarek** [comment]
Status on not-last commits are not updated, can be ignored.

**Comment by tasket** [comment]
More backlog coming tomorrow...

**Comment by andrewdavidwong** [comment]
> OK, I think you mean the BIOSTAR file. It was submitted that way, so I thought the script might have added the "unknown" text.

Actually, I was referring to the Asus-Z97. It has `'Asus TPM'`. `'unknown'` is fine. Many other TPM fields have that same value.

**Comment by tasket** [comment]
I see that `chipset-short` usually gets filled-in as the CPU generation codename. Also, the pci-ids site doesn't show regular chipset model numbers (like "QM77") for most of these IDs.

So instead of leaving the field empty I'll fill it in with the codename where applicable.

**Comment by andrewdavidwong** [comment]
Thanks, @tasket!

**Pull request merged**
