### PR TITLE
New HCL reports from 2020, manual clean-up

### PR DESCRIPTION
**Pull request by SvenSemmler**
Hi Andrew,

this PR contains all the HCL's submitted to qubes-users in 2020. In addition there is some manual cleanup:

- filenames are mostly OEM-Model-ID-Date-Time.yml 
- cleaned and unified the brand and model names ... the should make the list more tidy and easier to browse
- made sure that Intel integrated graphics are always called the same ("Integrated (Intel ..." but also contain the generation info
- cleaned-up the chip set code names to be always the same and correct 

Unfortunately, I am not aware how to test these changes to see how they will render on the website. Please let me know if there is a way.

### CODE REVIEW

**Comment by deeplow** [comment]
Hi @SvenSemmler there are also some reports that [landed on the forum](https://qubes-os.discourse.group/c/user-support/HCL-reports/23). Since you're a usual there would you also consider picking those up as well? (see [here](https://qubes-os.discourse.group/t/new-category-hcl-reports/555) a related discussion)

**Comment by SvenSemmler** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 11/29/20 7:35 AM, deeplow wrote:
> Since you're a usual there would you also consider picking those
> up as well?

Absolutely, I was simply unaware. Will do so today. Thanks for
pointing it out.

/Sven

- -- 
 public key: https://www.svensemmler.org/0x8F541FB6.asc
fingerprint: D7CA F2DB 658D 89BC 08D6 A7AA DA6E 167B 8F54 1FB6
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE18ry22WNibwI1qeq2m4We49UH7YFAl/DxrMACgkQ2m4We49U
H7ZZyRAA4Z0iZCx0iQ74NdskIscpaxJMUX1UrAyPBoTIu19U3WydLtDpAv5Gu7d6
HsBbbAtmxU2drH96t76VFzUrd0qMVLxy56cHIqxKXumCQ4740K6IKFsL6CWcv5FO
X4ziZQYHgjwDDeuJAOzyJhP7M2C8bidoX/0K/JEFcnJuRd+cdmcriZ+nGFKNHZWE
STVTt0mboRb0OiI4xXCTUBUu1vpw2JSMZj3MqLmNmByzn1Frp4dgyeIL8ffoDML1
Xey9uCuULwJ83A3vSTeaQdTgfRiA35dCxrLVwTzbfD90sFOmaXda8W0Scr4PW2XL
9nl1kVPcVGN22A7JBoDD30erWEyPtmqUJ2vTyTngiuz6S9fNtHEQiwpuR3CRb2tm
KYdB0LOHgjI4uYbhDg5KALYm+lBz+yF3mnTsh2EIR2dkwNTukQ2xrOr/g6rE440S
D9nycjnFavYlAksoctscLGHO9UKH2jHUbi/P03TrFgyY32Xo4L/YP07ryeUNwO7Z
WYxByBol0XTJ69VAR7WwR3GoE1p/Cu37P3tsP+FIBI9nssIYBEvL1FskoCM4sCRs
3qQzOTMp3T5H7ae1kMtRI2BgplVLBf+hKt6NU82xEXtReLSRf582AWBENDAaCVd/
UT2r0ra0OlrlBJ2o7Imx5St60TypwHEzPyWFKvTgWrCM7HSuDqI=
=OMl7
-----END PGP SIGNATURE-----

**Comment by andrewdavidwong** [comment]
Wonderful, thank you!

> Unfortunately, I am not aware how to test these changes to see how they will render on the website. Please let me know if there is a way.

Yes, it's documented here (tested in a Fedora VM):

https://github.com/QubesOS/qubesos.github.io#instructions

Please let me know if you run into any problems.

**Comment by SvenSemmler** [comment]
On 11/29/20 1:19 PM, Andrew David Wong wrote:
> https://github.com/QubesOS/qubesos.github.io#instructions

Thank you! I'll test and add the HCL's from the forum in the next days
(my estimations stink ... that's why I am hedging ;-)

**Comment by SvenSemmler** [comment]
form HCLs added, setting up test environment

**Comment by SvenSemmler** [comment]
@andrewdavidwong do I have to worry about the code-signing check failing?

**Comment by SvenSemmler** [comment]
@andrewdavidwong the docu of the code-signing check states: "please check if you have uploaded the key to a key server. "

I checked pool.sks-keyservers.net, keys.openpgp.org, pgp.mit.edu and keyserver.pgp.com -- all have my public key. Is there anything else I need to do?

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
@SvenSemmler your key expired (at least the one on the keyservers)

**Comment by marmarek** [comment]
testdeploy

**Comment by marmarek** [comment]
@SvenSemmler with new CI, we have test environment built in :)
After CI completes and no fatal error occurred (spellcheck issues are fine), you can post "testdeploy" comment and that version will be deployed into test env and linked to the PR (see "view deployment" link).

**Comment by SvenSemmler** [comment]
> @SvenSemmler your key expired (at least the one on the keyservers)

I removed the expiration date a while ago and resubmitted to the servers, but they might not like that. Shall I create a dedicated key for this task or will https://www.svensemmler.org/0x8F541FB6.asc do?

**Comment by marmarek** [comment]
This one will do, apparently not all keyservers have the updated one yet.

**Comment by SvenSemmler** [comment]
@andrewdavidwong after seeing the result I'd like to do a few more edits and will then ping you when I think it's ready -- ok?

e.g. "i7-6700K Skylake Integrated (Intel HD 530) Radeon RX" still reads a bit confusing ... "i7-6700K Skylake Integrated **Graphics** (Intel HD 530) **&** Radeon RX" looks nicer. 

Also I added plenty of "see email thread" and "see forum thread" but did not link them (only with the name). Want to fix that too.

Finally in some instances the BIOS line is extremely long and breaks the table layout somewhat. I'll fix that by shortening or breaking into multiple lines.

If you see other things you'd like me to fix, please let me know. I see this as an ongoing tasks (not only add, but improve) so we should probably publish soon and then iterate if that's ok with you.

**Comment by andrewdavidwong** [comment]
Sounds good. Thanks again!

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by marmarek** [comment]
> testdeploy

You need to wait for the CI build to complete.

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
@andrewdavidwong this PR is ready from my side. Please review/merge at your convenience.

**Comment by andrewdavidwong** [comment]
Wow, this is fantastic. Thank you for putting so much work into this!

**Comment by SvenSemmler** [comment]
> This one will do, apparently not all keyservers have the updated one yet.

Hi @marmarek  I am sorry to bother you with this. I have transitioned to a Nitrokey with an internally generated secret key. I would like to start using this also to sign my commits. Would you mind updating my public key with this one? 

 public key: https://www.svensemmler.org/2A632C537D744BC7.asc
fingerprint: DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7
[2A632C537D744BC7.asc.txt](https://github.com/QubesOS/qubes-hcl/files/6565471/2A632C537D744BC7.asc.txt)

**Comment by marmarek** [comment]
Done.

**Pull request merged**
