### PR TITLE
HCL reports from 1/8/23 to 1/26/23

### PR DESCRIPTION
**Pull request by SvenSemmler**
Doing this as a pull request in the hopes to see error messages (testdeploy) and being able to fix things without bothering marek. Not sure I have the power to merge pull requests... but if I can commit directly, I should be able to merge too.

### CODE REVIEW

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by SvenSemmler** [comment]
testdeploy

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRefresh

**Comment by marmarek** [comment]
Looks like reporting build status (gitlab->github) didn't work. I think I fixed it now, but can't test it on merged PR.

**Comment by SvenSemmler** [comment]
Unfortunately the new HCL still don't show on the website. I search for the reporters name e.g. "rodfeher" or "sheepskin" and get zero hits.

**Pull request merged**
