### PR TITLE
Add HCL report for ASUS-Q170M-C

### PR DESCRIPTION
**Pull request by tasket**
First one I'm uploading. :)
@andrewdavidwong I'll wait for you to check this before I PR the other new submissions.

### CODE REVIEW

**Comment by tasket** [comment]
Whoops! "No valid key" error. It shows as 'verified' in my copy of the project. Let me know if I'm missing something.

I followed the Alex Cabal instructions when setting up my key (incl. removing the original signing subkey). I don't know if that's the issue or something else.

**Comment by marmarek** [comment]
@tasket have you uploaded the public key to some keyserver? This is where the script look for keys.

@andrewdavidwong should I disable this script for qubes-hcl repository? It's mostly for code repositories...

**Comment by tasket** [comment]
@marmarek I was waiting to see if it worked before putting the key on a keyserver. I have just now sent it to pgp.mit.edu Fingerprint=BEE2 20C5 356E 764A 73EB  4AB3 1DC4 D106 F07F 1886

**Comment by marmarek** [comment]
Hmm, but the commit is signed with 448568C8B281C952 (not 1DC4D106F07F1886).

**Comment by tasket** [comment]
Would that be the sub-key?

**Comment by tasket** [comment]
Here is what my github profile says:
Email address: tasket@protonmail.com
Key ID: 1DC4D106F07F1886
Subkeys: 729CA8414F971D60, 448568C8B281C952 Added on Feb 9, 2017

The pgp server received the same info.

**Comment by marmarek** [comment]
Maybe the key haven't propagated yet to other keyservers.

**Comment by andrewdavidwong** [comment]
> First one I'm uploading. :)
> @andrewdavidwong I'll wait for you to check this before I PR the other new submissions.

Looks great, thanks!

> @andrewdavidwong should I disable this script for qubes-hcl repository? It's mostly for code repositories...

Since @tasket plans on signing all of his qubes-hcl commits, perhaps we should keep it for now.

**Comment by marmarek** [comment]
> Since @tasket plans on signing all of his qubes-hcl commits, perhaps we should keep it for now.

Ok.

**Pull request merged**
